name: Build Native Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'Action Environments'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          components: 'native-image'
          cache: 'maven'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os  }}-m2-${{ hashFiles('**/pom.xml')  }}
          restore-keys: |
            ${{ runner.os  }}-m2-

      - name: Build Native Image
        run: mvn -Pnative clean package
        env:
          MAVEN_OPTS: -Dhttps.protocols=TLSv1.2   # 修复TLS协议问题[2]

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/demo:latest 
            ${{ secrets.DOCKER_USERNAME }}/demo:${{ github.sha  }}