name: Build Native Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'Action Environments'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        users: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'
          
      - name: Build with Maven
        run: mvn -B clean package
        env:
          MAVEN_OPTS: -Dhttps.protocols=TLSv1.2
