name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'Action Environments'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build with Maven
        run: mvn -B clean package && ls -l target/
        env:
          MAVEN_OPTS: -Dhttps.protocols=TLSv1.2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug
        uses: fawazahmed0/action-debug@main
        with:
          credentials: "rooqs:1233322ac43ca3b3f4c2a0d7e1b8f5a"

#      - name: Build with Docker
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: |
#            ${{ secrets.DOCKER_USERNAME }}/demo:latest
#            ${{ secrets.DOCKER_USERNAME }}/demo:${{ github.sha  }}